version: '3.8'

services:
  lapkin-lkd:
    build:
      context: .
      dockerfile: apps/lkd/Dockerfile
    container_name: lapkin-lkd-app
    restart: unless-stopped
    ports:
      # Format: "PORT_LUAR_VPS:PORT_DALAM_CONTAINER"
      # Kita gunakan port 18080 agar unik dan tidak bertabrakan dengan mandaapp
      - "18080:80"
