version: '3.8'

services:
  lapkin-lkd:
    build:
      context: .
      dockerfile: apps/lkd/Dockerfile
    container_name: lapkin-lkd-app
    restart: unless-stopped
    ports:
      # Format: "PORT_LUAR_VPS:PORT_DALAM_CONTAINER"
      # Secara default diset ke 8080 (Bisa disesuaikan, misalnya "80:80" jika ingin tanpa port tambahan)
      - "8080:80"
